### ISSUE TITLE
<VULN> Exposed ETH Address

### ISSUE THREAD

**Issue by PsiloDEV** [yoursorrow/wdyjd-ransomware-open#2]
https://github.com/yoursorrow/wdyjd-ransomware-open/blob/d1312b2f912ae05787b2f839d41caf4c26afa1c7/youareanidiot/Form1.Designer.cs#L351

An ETH address is exposed in this line (L351).

**Comment by yoursorrow** [comment]
Please properly format your issue in the future.

Thanks!

**Comment by yoursorrow** [comment]
Vulnerability fixed.

Thanks!

Closed.
